#!/usr/bin/env bash
#
# Layered cache-busting toolkit — runs as a prebuild step (and also predev so
# the badge is fresh in dev). What this script does:
#
#   1. Generates a build-id token combining git short SHA + UTC timestamp.
#   2. Writes the token to `src/build-id.generated.ts` so the UI badge
#      displays it. Vite content-hashes the resulting bundle automatically.
#   3. Writes `public/build-id.json` for an out-of-band sanity check
#      (`curl /build-id.json` after deploy returns the live build).
#
# Defense in depth: Vite content-hashes assets; meta no-cache stops HTML
# revalidation; the build-id badge in the UI lets a human see which build
# is live in the browser at a glance.

set -euo pipefail
cd "$(dirname "$0")/.."

ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EPOCH=$(date -u +%s)

if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
  SHA=$(git rev-parse --short=8 HEAD 2>/dev/null || echo "nogit")
  DIRTY=""
  if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    DIRTY="-dirty"
  fi
else
  SHA="nogit"
  DIRTY=""
fi

BUILD_ID="${SHA}${DIRTY}-${EPOCH}"

cat > src/build-id.generated.ts <<EOF
// AUTO-GENERATED by scripts/bust.sh — do not edit.
export const BUILD_ID = '${BUILD_ID}';
export const BUILD_ISO = '${ISO}';
export const BUILD_SHA = '${SHA}${DIRTY}';
EOF

mkdir -p public
cat > public/build-id.json <<EOF
{
  "build_id": "${BUILD_ID}",
  "sha": "${SHA}${DIRTY}",
  "iso": "${ISO}",
  "epoch": ${EPOCH}
}
EOF

echo "[bust] build-id=${BUILD_ID}"
